name: Metrics

on:
  schedule:
    - cron: "* * * * *"  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Aline-CROIRE
          base: header, repositories
          plugin_activity: yes
          plugin_languages: yes
